<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}

	public function findAllPending()
	{
		return $this->findBy(array('bookingstatus' => '1'), array('id' => 'DESC'));
	}
	
	public function findRoomById($room_id){
		return $this->getEntityManager()
			->createQuery('SELECT r FROM ModelBundle:Room r WHERE r.id='.$room_id)->getResult();
	}
}