<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BulkavailableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulkavailableRepository extends EntityRepository
{
	public function findAvailableRooms() {
		$query = $this->getEntityManager()->createQuery('SELECT ba FROM ModelBundle:Bulkavailable ba WHERE ba.qty<>0');
		try {
			return $query->getResult();
		} catch(\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
