<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	
	public function countUnreadMessages()
	{
		return $this->getEntityManager()
				->createQuery(
					'SELECT COUNT(c.id) as totalmessages FROM ModelBundle:Contact c WHERE c.isread=0'
				)->getResult();
	}
}