<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HomepagefacilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepagefacilityRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	
	public function findAllActive()
	{
		return $this->getEntityManager()->createQuery('SELECT t FROM ModelBundle:Homepagefacility t WHERE t.status=1 ORDER BY t.id DESC')->getResult();
	}
}
