<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	
	public function findLastThree()
	{
		return $this->getEntityManager()->createQuery('SELECT n FROM ModelBundle:News n ORDER BY n.id DESC')->setMaxResults(4)->getResult();
	}
}
