<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	
	public function findAllActiveGalleryHighlights()
	{
		return $this->getEntityManager()->createQuery('SELECT p FROM ModelBundle:Photo p WHERE p.galleryHighlight=1 AND p.status=1 ORDER BY p.id DESC')->getResult();
	}
}