<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoomclosureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomclosureRepository extends EntityRepository
{
}
