<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('roomOrder' => 'ASC'));
	}
	
	public function findAllActive()
	{
		return $this->getEntityManager()->createQuery('SELECT r FROM ModelBundle:Room r WHERE r.status=1 ORDER BY r.roomOrder ASC')->getResult();
	}
	
	public function findAllActiveGuestFavourite()
	{
		return $this->getEntityManager()->createQuery('SELECT r FROM ModelBundle:Room r WHERE r.guestFavourite=1 AND r.status=1 ORDER BY r.roomOrder ASC')->setMaxResults(3)->getResult();
	}
	
	public function checkIfAvailable($roomid)
	{
		return $this->getEntityManager()->createQuery('SELECT r.id FROM ModelBundle:Room r WHERE r.id='.$roomid.' AND r.isAvailable=1 AND r.status=1')->getResult();
	}
}