<?php

namespace Renz\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	
	public function findAllActive()
	{
		return $this->getEntityManager()->createQuery('SELECT s FROM ModelBundle:Slider s WHERE s.status=1 ORDER BY s.id ASC')->getResult();
	}
}
